name: JDDock

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download and install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg aria2
          wget -qq ${{ secrets.CONFIG }}
      - name: Running Script
        run:  python main.py